### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by johnran103** [Cuogeihong/CEASC#1]
In the repo, you said use ./tools/test.py to evaluate the result. How did you handle the ignore region in Visdrone? The original matlab script drops gts and dets in ignore region.

**Comment by Cuogeihong** [comment]
Actually, the README.md has not been fully updated yet. You can refer to [vis_pkl.py](https://github.com/Cuogeihong/CEASC/blob/main/tools/vis_pkl.py) and [json_to_txt.py](https://github.com/Cuogeihong/CEASC/blob/main/tools/json_to_txt.py) and use the following scripts to obtain VisDrone format result in pred_txt/ folder.
```bash
python tools/test.py /path/to/config-file /path/to/work-dir/latest.pth --out path/to/result.pkl
python tools/vis_pkl.py --pkl_pathname path/to/result.pkl --json_pathname path/to/result.json
python tools/json_to_txt.py --json_pathname path/to/result.json
```

**Comment by johnran103** [comment]
Got it. Thank you.
