### ISSUE TITLE
How to set the lr?

### ISSUE THREAD

**Issue by hefangnan** [Cuogeihong/CEASC#13]
great work!
Iwant to know If I had 2 gpu,each gpu batch size is 8,then how should I set the lr?

**Comment by Cuogeihong** [comment]
According to our experimnets, keeping original lr 0.01 is ok. you can also try 0.005, 0.0025 or 0.00125 for instance

**Comment by hefangnan** [comment]
> According to our experimnets, keeping original lr 0.01 is ok. you can also try 0.005, 0.0025 or 0.00125 for instance


感谢你的快速回复，我将学习率设置为了0.02，但在训练的时候出现了mmdet - ERROR - The testing results of the whole dataset is empty.请问这是不是和学习率设置过大有关？
![Snipaste_2023-09-10_21-19-45](https://github.com/Cuogeihong/CEASC/assets/52640516/caec9e60-e114-4f0f-887e-b98fec82a269)

**Comment by Cuogeihong** [comment]
是的，0.02有一点大了。但这个错误也可能是数据集的问题。你可以使用论文的设置，将每个gpu的batchsize改成2，用0.01的lr训练，避免学习率问题

**Comment by hefangnan** [comment]
> 是的，0.02有一点大了。但这个错误也可能是数据集的问题。你可以使用论文的设置，将每个gpu的batchsize改成2，用0.01的lr训练，避免学习率问题

谢谢您的建议，我把学习率调为了0.005就正常了

**Comment by hefangnan** [comment]
> 是的，0.02有一点大了。但这个错误也可能是数据集的问题。你可以使用论文的设置，将每个gpu的batchsize改成2，用0.01的lr训练，避免学习率问题

另外我还想问一下，论文中的mAp是IoU=030:0.95的还是IoU=0.50：0.95的？
