### ISSUE TITLE
关于实验结果的复现

### ISSUE THREAD

**Issue by hefangnan** [Cuogeihong/CEASC#14]
在对ceasc的gfl进行复现时，使用的是您提供的训练权重，在visdrone上进行eval，AP和论文中基本一致，但是AR却相差的很大，请问是什么原因导致的呢？
![Snipaste_2023-09-14_16-57-12](https://github.com/Cuogeihong/CEASC/assets/52640516/9efaac39-6096-438f-a7c5-bc5fd7870ffc)

**Comment by hefangnan** [comment]
而且我在使用您提供的配置文件进行训练的时候，有时会出现最新的epoch在验证集上的mAp较上一个epoch相比有所下降，请问这是正常的吗？例如epoch7和epoch8相比，epoch12和epoch13相比，都出现了不同程度的下降
[20230914_132640.log](https://github.com/Cuogeihong/CEASC/files/12614717/20230914_132640.log)

**Comment by Cuogeihong** [comment]
你可以参考 #1 和 #2 ，检查dataset、matlab脚本以及后处理脚本。

部分epoch结果的下降是正常的，当然你也可以根据自己的结果适当调整训练设置。此外，建议你config中的dataset type与我提供的config保持一致

**Comment by hefangnan** [comment]
为什么我使用您提供的config训练出来的模型权重文件里的retina检测头部分少了相应的depth_wise conv的部分？
zhe's这是您提供的权重文件里的state_dict的key
![res](https://github.com/Cuogeihong/CEASC/assets/52640516/759a6331-c29c-4aed-85ea-833909e4a4dd)
这是我使用您提供的config训练出来的权重文件的key
![Snipaste_2023-09-16_16-34-38](https://github.com/Cuogeihong/CEASC/assets/52640516/e448ba04-052c-4e99-9fe8-651df9d83606)
可以看出少了depth_wise conv相应的权重，请问我应该在原有代码的哪一部分做出修改加上depth_wise conv呢？

**Comment by hefangnan** [comment]
> 你可以参考 #1 和 #2 ，检查dataset、matlab脚本以及后处理脚本。
> 
> 部分epoch结果的下降是正常的，当然你也可以根据自己的结果适当调整训练设置。此外，建议你config中的dataset type与我提供的config保持一致

我好像找到了相应的原因，在使用您提供的配置文件dynamic_retinanet_res18_visdrone.py进行训练后，在得到的权重文件的retina检测头部分我发现好像并没有AMM Module和Point-wise Conv对应的权重，只有gn和xi的权重，请问这种是因为什么原因呢？
![111](https://github.com/Cuogeihong/CEASC/assets/52640516/a0e5b2d3-033f-436c-85e8-e254fbea00a7)

**Comment by hefangnan** [comment]
> 你可以参考 #1 和 #2 ，检查dataset、matlab脚本以及后处理脚本。
> 
> 部分epoch结果的下降是正常的，当然你也可以根据自己的结果适当调整训练设置。此外，建议你config中的dataset type与我提供的config保持一致

好的，谢谢您的建议。但是在我检查模型的权重文件时我发现了不一样的地方
这是我使用您提供的config文件里的dynamic_retinanet_res18_visdrone.py训练出来的权重文件
![111](https://github.com/Cuogeihong/CEASC/assets/52640516/19cc3583-8efb-4ca4-b7df-bbfda87e026f)
这是从您仓库下载的您提供的训练好了的RetinaNet CEASC的权重文件
![res](https://github.com/Cuogeihong/CEASC/assets/52640516/b645ae70-09b8-4a87-9d1e-429a02375191)
可以看到每层都少了bbox_head.cls_convs.0.0.conv.depth_wise.0.weight和bbox_head.cls_convs.0.0.conv.depth_wise.0.bias，对应的reg_convs也少了这一部分，请问这是什么原因呢？

**Comment by Cuogeihong** [comment]
depth_wise层并没有参与训练或推理，缺少这一部分并没有影响

**Comment by hefangnan** [comment]
好的，谢谢！
