### ISSUE TITLE
About spconv

### ISSUE THREAD

**Issue by yinnengzhong** [Cuogeihong/CEASC#19]
ImportError: /opt/conda/lib/python3.7/site-packages/sparse_conv-0.0.0-py3.7-linux-x86_64.egg/sparse_conv.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at8internal23OpaqueOptionalTensorRefD1EvImportError
: /opt/conda/lib/python3.7/site-packages/sparse_conv-0.0.0-py3.7-linux-x86_64.egg/sparse_conv.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at8internal23OpaqueOptionalTensorRefD1Ev

I followed your steps to install spconv, but I got this error when I import spconv.  My environment is pytorch 1.10.0 cuda 11.3 python 3.7.

**Comment by Czeni1** [comment]
您好，我也遇到这个问题了，请问您解决了嘛？
