### ISSUE TITLE
GFL v1 reimplementation performance question.

### ISSUE THREAD

**Issue by johnran103** [Cuogeihong/CEASC#2]
I used your config baseline_gfl_res18_visdrone.py without change. The result is below(tested with matlab 2021a).
![截屏2023-03-30 19 05 59](https://user-images.githubusercontent.com/94056614/228817239-780f71e5-5536-4100-9b8d-c1db4cb9ec6b.png)

which is far below your paper result AP 28.4, AP50 50.0.
![截屏2023-03-30 19 01 38](https://user-images.githubusercontent.com/94056614/228816297-f953de91-ed9e-45e2-9be9-c8e7dbd85932.png)

What is the possible reseason? Could you give me your checkpoint or possible explanation, please!

**Comment by Cuogeihong** [comment]
Hello, please provide me with the mmdetection training log. By the way, the checkpoints has been updated.

**Comment by johnran103** [comment]
[20230329_125746.log](https://github.com/Cuogeihong/CEASC/files/11119861/20230329_125746.log)
Hello, this is my training log. Thank you !

**Comment by johnran103** [comment]
By the way, these two result come from your checkpoint.
First, test with defualt coco scripts.
![截屏2023-03-31 16 57 43](https://user-images.githubusercontent.com/94056614/229075393-9368515f-1865-4a68-a9c7-dabf4548bd91.png)
Second, test with ignored region.
![截屏2023-03-31 16 57 55](https://user-images.githubusercontent.com/94056614/229075697-b9533e4c-29bc-466e-bc1f-d74ce0312cfb.png)

**Comment by Cuogeihong** [comment]
> [20230329_125746.log](https://github.com/Cuogeihong/CEASC/files/11119861/20230329_125746.log) Hello, this is my training log. Thank you !

it seems the training phase works fine, and the post-process also works in my computer

![image](https://user-images.githubusercontent.com/39731755/229074531-6d353bdf-7006-489e-aab6-9d905b8c5133.png)

so you could check the dataset format following [UFPMP-Det](https://github.com/PuAnysh/UFPMP-Det) and check the [official val script](https://github.com/VisDrone/VisDrone2018-DET-toolkit)
or check out the path in https://github.com/Cuogeihong/CEASC/blob/6546f7bb945b6e4579b5b54574b2fb4f417be2e5/tools/json_to_txt.py#L14

By the way, it seems that all your classes' AP are lower than mine (using my checkpoint): 
```
class1: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 25.02%.
class2: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 15.54%.
class3: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 11.45%.
class4: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 59.02%.
class5: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 37.53%.
class6: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 28.76%.
class7: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 19.67%.
class8: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 11.65%.
class9: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 45.94%.
class10: Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 25.61%.
Evaluation Completed. The peformance of the detector is presented as follows.
Average Precision  (AP) @[ IoU=0.50:0.95 | maxDets=500 ] = 28.37%.
```

**Comment by Cuogeihong** [comment]
> By the way, these two result come from your checkpoint. First, test with defualt coco scripts. ![截屏2023-03-31 16 57 43](https://user-images.githubusercontent.com/94056614/229075393-9368515f-1865-4a68-a9c7-dabf4548bd91.png) Second, test with ignored region. ![截屏2023-03-31 16 57 55](https://user-images.githubusercontent.com/94056614/229075697-b9533e4c-29bc-466e-bc1f-d74ce0312cfb.png)

Also, here is my test with defualt coco scripts.
![image](https://user-images.githubusercontent.com/39731755/229077870-19cefc93-7d67-47dc-a8ba-94362d37600c.png)
I think it is probably because of the wrong dataset format

**Comment by johnran103** [comment]
Here is my pipeline to prepare & test visdrone dataset:
1. Download visdrone dataset from from its official website.
2. Using the script from UFPMP-Det python UFPMP-Det-Tools/build_dataset/VisDrone2COCO.py xxx xxx xxx/instances_UAVval_v1.json
3. Test. CUDA_VISIBLE_DEVICES=1 python ./tools/test.py ./configs/UAV/baseline_gfl_res18_visdrone.py ./epoch_15.pth --eval bbox --out ./result.pkl
python tools/vis_pkl.py --pkl_pathname ./result.pkl --json_pathname ./result.json
python tools/json_to_txt.py --json_pathname ./result.json
matlab -r evalDET
The defualt coco results are as follow. But matlab test results are **not changed**.
![截屏2023-04-03 15 14 27](https://user-images.githubusercontent.com/94056614/229437679-7c7aaa87-383d-4b3c-b466-c4ac1755c896.png)

**Comment by johnran103** [comment]
I tested your ceasc model. Which is fine.
![截屏2023-04-03 15 46 40](https://user-images.githubusercontent.com/94056614/229444819-eba5b29d-9ad1-4085-8664-7e81a733f8df.png)

**Comment by Cuogeihong** [comment]
I have fixed a bug in gfl baseline, you can test it again. By the way, matlab test results not changed while coco changed seems strange, maybe you used a wrong pred_txt/ folder for test?

**Comment by johnran103** [comment]
Ufter using your fixed code and checkpoint, I can get your performance now.

**Comment by Greatxcw** [comment]
> By the way, these two result come from your checkpoint. First, test with defualt coco scripts. ![截屏2023-03-31 16 57 43](https://user-images.githubusercontent.com/94056614/229075393-9368515f-1865-4a68-a9c7-dabf4548bd91.png) Second, test with ignored region. ![截屏2023-03-31 16 57 55](https://user-images.githubusercontent.com/94056614/229075697-b9533e4c-29bc-466e-bc1f-d74ce0312cfb.png)

Hello, I am also reproducing the code ,could tell me how  to test  with ignored region，please!

**Comment by johnran103** [comment]
Use the official MATLAB code provided by the VisDrone team.



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/13/2023 21:43 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Cuogeihong/CEASC] GFL v1 reimplementation performance question. (Issue #2) |

By the way, these two result come from your checkpoint. First, test with defualt coco scripts. Second, test with ignored region.

Hello, I am also reproducing the code ,could tell me how to test with ignored region，please!

**Comment by Greatxcw** [comment]
> Use the official MATLAB code provided by the VisDrone team.
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 10/13/2023 21:43 | | To | ***@***.***> | | Cc | ***@***.***>***@***.***> | | Subject | Re: [Cuogeihong/CEASC] GFL v1 reimplementation performance question. (Issue #2) | By the way, these two result come from your checkpoint. First, test with defualt coco scripts. Second, test with ignored region. Hello, I am also reproducing the code ,could tell me how to test with ignored region，please! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
Got it,thank you very much!

**Comment by QingfanHou** [comment]
> Here is my pipeline to prepare & test visdrone dataset:
> 
> 1. Download visdrone dataset from from its official website.
> 2. Using the script from UFPMP-Det python UFPMP-Det-Tools/build_dataset/VisDrone2COCO.py xxx xxx xxx/instances_UAVval_v1.json
> 3. Test. CUDA_VISIBLE_DEVICES=1 python ./tools/test.py ./configs/UAV/baseline_gfl_res18_visdrone.py ./epoch_15.pth --eval bbox --out ./result.pkl
>    python tools/vis_pkl.py --pkl_pathname ./result.pkl --json_pathname ./result.json
>    python tools/json_to_txt.py --json_pathname ./result.json
>    matlab -r evalDET
>    The defualt coco results are as follow. But matlab test results are **not changed**.
>    ![截屏2023-04-03 15 14 27](https://user-images.githubusercontent.com/94056614/229437679-7c7aaa87-383d-4b3c-b466-c4ac1755c896.png)
I encountered the same problem as you. Were you able to achieve results similar to the author's in your subsequent training? After processing the data as you mentioned above, the results I trained myself had an mAP of around 0.25 when validated on mmdet.
